package com.productos.integracion.mahalo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-23T16:19:00.566-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ExternalServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ExternalServiceSoap {

    @WebMethod(operationName = "SetModificacionCliente", action = "http://tempuri.org/SetModificacionCliente")
    @RequestWrapper(localName = "SetModificacionCliente", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificacionCliente")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificacionCliente(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetModificacionCliente", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetModificacionCliente encabezadoSetModificacionCliente
    );

    @WebMethod(operationName = "GetModificacionClienteMasivo", action = "http://tempuri.org/GetModificacionClienteMasivo")
    @RequestWrapper(localName = "GetModificacionClienteMasivo", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetModificacionClienteMasivo")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getModificacionClienteMasivo(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetModificacionClienteMasivo", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetModificacionClienteMasivo encabezadoGetModificacionClienteMasivo
    );

    @WebMethod(operationName = "SetGenerarFactura", action = "http://tempuri.org/SetGenerarFactura")
    @RequestWrapper(localName = "SetGenerarFactura", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetGenerarFactura")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setGenerarFactura(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetGenerarFactura", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetGenerarFactura encabezadoSetGenerarFactura,
        @WebParam(name = "DetalleProductos", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfVenta detalleProductos,
        @WebParam(name = "FormaPagoFactura", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.FormaPagoFactura formaPagoFactura
    );

    @WebMethod(operationName = "GetSaldoxBarra", action = "http://tempuri.org/GetSaldoxBarra")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxBarra(
        @WebParam(partName = "parameters", name = "SaldoxBarra", targetNamespace = "http://tempuri.org/")
        SaldoxBarra parameters
    );

    @WebMethod(operationName = "SetModificacionMascota", action = "http://tempuri.org/SetModificacionMascota")
    @RequestWrapper(localName = "SetModificacionMascota", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificacionMascota")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificacionMascota(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoMascota", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoMascota encabezadoMascota,
        @WebParam(name = "DetalleMascota", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfMascotaModificacion detalleMascota
    );

    @WebMethod(operationName = "GetCreacionClienteMasivo", action = "http://tempuri.org/GetCreacionClienteMasivo")
    @RequestWrapper(localName = "GetCreacionClienteMasivo", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetCreacionClienteMasivo")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getCreacionClienteMasivo(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetCreacionClienteMasivo", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetCreacionClienteMasivo encabezadoGetCreacionClienteMasivo
    );

    @WebMethod(operationName = "GetSaldoxReferenciaProveedor", action = "http://tempuri.org/GetSaldoxReferenciaProveedor")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxReferenciaProveedor(
        @WebParam(partName = "parameters", name = "SaldoxReferenciaProveedor", targetNamespace = "http://tempuri.org/")
        SaldoxReferenciaProveedor parameters
    );

    @WebMethod(operationName = "GetClienteMascota", action = "http://tempuri.org/GetClienteMascota")
    @RequestWrapper(localName = "GetClienteMascota", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetClienteMascota")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getClienteMascota(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetClienteMascota", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetClienteMascota encabezadoGetClienteMascota
    );

    @WebMethod(operationName = "SetCrearMultiplesPlu", action = "http://tempuri.org/SetCrearMultiplesPlu")
    @RequestWrapper(localName = "SetCrearMultiplesPlu", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetCrearMultiplesPlu")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setCrearMultiplesPlu(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "DetalleMPlu", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayDeMultiplesPlu detalleMPlu,
        @WebParam(name = "sw_generaPlu", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.SwGeneraPlu swGeneraPlu
    );

    @WebMethod(operationName = "GetSaldoxReferencia", action = "http://tempuri.org/GetSaldoxReferencia")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxReferencia(
        @WebParam(partName = "parameters", name = "SaldoxReferencia", targetNamespace = "http://tempuri.org/")
        SaldoxReferencia parameters
    );

    @WebMethod(operationName = "GetSaldosCreadosMasivoxAlmacen", action = "http://tempuri.org/GetSaldosCreadosMasivoxAlmacen")
    @RequestWrapper(localName = "GetSaldosCreadosMasivoxAlmacen", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetSaldosCreadosMasivoxAlmacen")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getSaldosCreadosMasivoxAlmacen(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetSaldosCreadosMasivoxAlmacen", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetSaldosCreadosMasivoxAlmacen encabezadoGetSaldosCreadosMasivoxAlmacen
    );

    @WebMethod(operationName = "GetVentasxMascotas", action = "http://tempuri.org/GetVentasxMascotas")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getVentasxMascotas(
        @WebParam(partName = "parameters", name = "VentasxMascotas", targetNamespace = "http://tempuri.org/")
        VentasxMascotas parameters
    );

    @WebMethod(operationName = "GetConsecutivoFacturacion", action = "http://tempuri.org/GetConsecutivoFacturacion")
    @RequestWrapper(localName = "GetConsecutivoFacturacion", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetConsecutivoFacturacion")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getConsecutivoFacturacion(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication
    );

    @WebMethod(operationName = "SetCancelarPedido", action = "http://tempuri.org/SetCancelarPedido")
    @RequestWrapper(localName = "SetCancelarPedido", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetCancelarPedido")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setCancelarPedido(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetCancelarPedido", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetCancelarPedido encabezadoSetCancelarPedido
    );

    @WebMethod(operationName = "SetGenerarKardex", action = "http://tempuri.org/SetGenerarKardex")
    @RequestWrapper(localName = "SetGenerarKardex", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetGenerarKardex")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setGenerarKardex(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetGenerarKardex", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetGenerarKardex encabezadoSetGenerarKardex,
        @WebParam(name = "DetalleProductosKardex", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfKardex detalleProductosKardex
    );

    @WebMethod(operationName = "GetplanoContableAX_empleado", action = "http://tempuri.org/GetplanoContableAX_empleado")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getplanoContableAXEmpleado(
        @WebParam(partName = "parameters", name = "planoContableAX_empleado", targetNamespace = "http://tempuri.org/")
        PlanoContableAXEmpleado parameters
    );

    @WebMethod(operationName = "GetSaldoxSkuAlmacen", action = "http://tempuri.org/GetSaldoxSkuAlmacen")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxSkuAlmacen(
        @WebParam(partName = "parameters", name = "SaldoxSkuAlmacen", targetNamespace = "http://tempuri.org/")
        SaldoxSkuAlmacen parameters
    );

    @WebMethod(operationName = "GetInfoCreacionProductoMasivo", action = "http://tempuri.org/GetInfoCreacionProductoMasivo")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getInfoCreacionProductoMasivo(
        @WebParam(partName = "parameters", name = "CreacionProductoMasivo", targetNamespace = "http://tempuri.org/")
        CreacionProductoMasivo parameters
    );

    @WebMethod(operationName = "GetInfoModificacionProductoMasivo", action = "http://tempuri.org/GetInfoModificacionProductoMasivo")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getInfoModificacionProductoMasivo(
        @WebParam(partName = "parameters", name = "ModificacionProductoMasivo", targetNamespace = "http://tempuri.org/")
        ModificacionProductoMasivo parameters
    );

    @WebMethod(operationName = "GetCliente", action = "http://tempuri.org/GetCliente")
    @RequestWrapper(localName = "GetCliente", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetCliente")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getCliente(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetCliente", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetCliente encabezadoGetCliente
    );

    @WebMethod(operationName = "GetSaldoxReferenciaAlmacen", action = "http://tempuri.org/GetSaldoxReferenciaAlmacen")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxReferenciaAlmacen(
        @WebParam(partName = "parameters", name = "SaldoxReferenciaAlmacen", targetNamespace = "http://tempuri.org/")
        SaldoxReferenciaAlmacen parameters
    );

    @WebMethod(action = "http://tempuri.org/setMultiplesListaDePrecios")
    @RequestWrapper(localName = "setMultiplesListaDePrecios", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetMultiplesListaDePrecios")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setMultiplesListaDePrecios(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "ListaDePrecios", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfListaPrecios listaDePrecios
    );

    @WebMethod(operationName = "GetEmailxVentas", action = "http://tempuri.org/GetEmailxVentas")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getEmailxVentas(
        @WebParam(partName = "parameters", name = "EmailxVentas", targetNamespace = "http://tempuri.org/")
        EmailxVentas parameters
    );

    @WebMethod(operationName = "GetInfoProductoxSku", action = "http://tempuri.org/GetInfoProductoxSku")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getInfoProductoxSku(
        @WebParam(partName = "parameters", name = "ProductoxSku", targetNamespace = "http://tempuri.org/")
        ProductoxSku parameters
    );

    @WebMethod(operationName = "SetClienteNuevo", action = "http://tempuri.org/SetClienteNuevo")
    @RequestWrapper(localName = "SetClienteNuevo", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetClienteNuevo")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setClienteNuevo(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetClienteNuevo", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetClienteNuevo encabezadoSetClienteNuevo
    );

    @WebMethod(operationName = "GetSaldoxSku", action = "http://tempuri.org/GetSaldoxSku")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxSku(
        @WebParam(partName = "parameters", name = "SaldoxSku", targetNamespace = "http://tempuri.org/")
        SaldoxSku parameters
    );

    @WebMethod(operationName = "SetNuevoMascota", action = "http://tempuri.org/SetNuevoMascota")
    @RequestWrapper(localName = "SetNuevoMascota", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetNuevoMascota")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setNuevoMascota(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoMascota", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoMascota encabezadoMascota,
        @WebParam(name = "DetalleMascota", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfMascota detalleMascota
    );

    @WebMethod(operationName = "GetPlanoContableAXR", action = "http://tempuri.org/GetPlanoContableAXR")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getPlanoContableAXR(
        @WebParam(partName = "parameters", name = "PlanoContableAXR", targetNamespace = "http://tempuri.org/")
        PlanoContableAXR parameters
    );

    @WebMethod(operationName = "GetSeparado", action = "http://tempuri.org/GetSeparado")
    @RequestWrapper(localName = "GetSeparado", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetSeparado")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getSeparado(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetSeparado", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetSeparado encabezadoGetSeparado
    );

    @WebMethod(action = "http://tempuri.org/setModificarMultiplesListaDePrecios")
    @RequestWrapper(localName = "setModificarMultiplesListaDePrecios", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificarMultiplesListaDePrecios")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificarMultiplesListaDePrecios(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "ModificarListaDePrecios", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfModificarListaPrecios modificarListaDePrecios
    );

    @WebMethod(operationName = "SetModificacionPuntosCliente", action = "http://tempuri.org/SetModificacionPuntosCliente")
    @RequestWrapper(localName = "SetModificacionPuntosCliente", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificacionPuntosCliente")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificacionPuntosCliente(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetModificacionPuntosCliente", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetModificacionPuntosCliente encabezadoSetModificacionPuntosCliente
    );

    @WebMethod(operationName = "GetSaldosCreadosMasivo", action = "http://tempuri.org/GetSaldosCreadosMasivo")
    @RequestWrapper(localName = "GetSaldosCreadosMasivo", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetSaldosCreadosMasivo")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getSaldosCreadosMasivo(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetSaldosCreadosMasivo", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetSaldosCreadosMasivo encabezadoGetSaldosCreadosMasivo
    );

    @WebMethod(operationName = "SetMultiplesNuevasReferencias", action = "http://tempuri.org/SetMultiplesNuevasReferencias")
    @RequestWrapper(localName = "SetMultiplesNuevasReferencias", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetMultiplesNuevasReferencias")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setMultiplesNuevasReferencias(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "DetalleMReferencias", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayDeMultiplesReferencias detalleMReferencias,
        @WebParam(name = "sw_validaRefProveedor", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.SwValidaRefProveedor swValidaRefProveedor,
        @WebParam(name = "sw_generaReferencias", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.SwValidaRefProveedor swGeneraReferencias
    );

    @WebMethod(operationName = "SetCrearFormaPagoFactura", action = "http://tempuri.org/SetCrearFormaPagoFactura")
    @RequestWrapper(localName = "SetCrearFormaPagoFactura", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetCrearFormaPagoFactura")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setCrearFormaPagoFactura(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetCrearFormaPagoFactura", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetCrearFormaPagoFactura encabezadoSetCrearFormaPagoFactura,
        @WebParam(name = "FormaPagoFactura", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.FormaPagoFactura formaPagoFactura
    );

    @WebMethod(operationName = "SetGenerarSeparado", action = "http://tempuri.org/SetGenerarSeparado")
    @RequestWrapper(localName = "SetGenerarSeparado", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetGenerarSeparado")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setGenerarSeparado(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoSetGenerarSeparado", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoSetGenerarSeparado encabezadoSetGenerarSeparado,
        @WebParam(name = "DetalleProductosSeparado", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayOfSeparado detalleProductosSeparado
    );

    @WebMethod(operationName = "GetSaldosModificadosMasivoxAlmacen", action = "http://tempuri.org/GetSaldosModificadosMasivoxAlmacen")
    @RequestWrapper(localName = "GetSaldosModificadosMasivoxAlmacen", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetSaldosModificadosMasivoxAlmacen")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getSaldosModificadosMasivoxAlmacen(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetSaldosModificadosMasivoxAlmacen", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetSaldosModificadosMasivoxAlmacen encabezadoGetSaldosModificadosMasivoxAlmacen
    );

    @WebMethod(operationName = "GetSaldosModificadosMasivo", action = "http://tempuri.org/GetSaldosModificadosMasivo")
    @RequestWrapper(localName = "GetSaldosModificadosMasivo", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.GetSaldosModificadosMasivo")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS getSaldosModificadosMasivo(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "EncabezadoGetSaldosModificadosMasivo", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.EncabezadoGetSaldosModificadosMasivo encabezadoGetSaldosModificadosMasivo
    );

    @WebMethod(operationName = "GetSaldoxBarraAlmacen", action = "http://tempuri.org/GetSaldoxBarraAlmacen")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxBarraAlmacen(
        @WebParam(partName = "parameters", name = "SaldoxBarraAlmacen", targetNamespace = "http://tempuri.org/")
        SaldoxBarraAlmacen parameters
    );

    @WebMethod(operationName = "GetSaldoxReferenciaProveedorAlmacen", action = "http://tempuri.org/GetSaldoxReferenciaProveedorAlmacen")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getSaldoxReferenciaProveedorAlmacen(
        @WebParam(partName = "parameters", name = "SaldoxReferenciaProveedorAlmacen", targetNamespace = "http://tempuri.org/")
        SaldoxReferenciaProveedorAlmacen parameters
    );

    @WebMethod(operationName = "SetModificarMultiplesReferencias", action = "http://tempuri.org/SetModificarMultiplesReferencias")
    @RequestWrapper(localName = "SetModificarMultiplesReferencias", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificarMultiplesReferencias")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificarMultiplesReferencias(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "DetalleMReferencias", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayDeMultiplesReferencias detalleMReferencias,
        @WebParam(name = "sw_validaRefProveedor", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.SwValidaRefProveedor swValidaRefProveedor
    );

    @WebMethod(operationName = "SetModificarMultiplesPlu", action = "http://tempuri.org/SetModificarMultiplesPlu")
    @RequestWrapper(localName = "SetModificarMultiplesPlu", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.SetModificarMultiplesPlu")
    @ResponseWrapper(localName = "TicketResponse", targetNamespace = "http://tempuri.org/", className = "com.productos.integracion.mahalo.TicketResponse")
    @WebResult(name = "ResultadoTicket", targetNamespace = "http://tempuri.org/")
    public com.productos.integracion.mahalo.ResultadoWS setModificarMultiplesPlu(
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.AuthenticationSoapHeader authentication,
        @WebParam(name = "DetalleMPlu", targetNamespace = "http://tempuri.org/")
        com.productos.integracion.mahalo.ArrayDeMultiplesPlu detalleMPlu
    );

    @WebMethod(operationName = "GetplanoContableAX_detallado", action = "http://tempuri.org/GetplanoContableAX_detallado")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TicketResponse", targetNamespace = "http://tempuri.org/", partName = "parameters_exit")
    public TicketResponse getplanoContableAXDetallado(
        @WebParam(partName = "parameters", name = "planoContableAX_detallado", targetNamespace = "http://tempuri.org/")
        PlanoContableAXDetallado parameters
    );
}
